### ISSUE TITLE
Improve the SPIFFE integration to avoid the need of storing certificates on disk

### ISSUE THREAD

**Issue by amartinezfayo** [spiffe/spiffe-nginx#11]
Current implementation relies on storing certificates on disk and reload the configuration when new certificates are available.

Improve the implementation to update the SSL context in memory, without the need of storing certificates on disk.

**Comment by MarcosDY** [comment]
In current implementation, we are sending SIGHUP signal, it cause some issues, basically the fact that some requests are lost when trying to call nginx at the same time sighup is send, and its actually reloading.

To prevent it, we are actually trying to move all logic from current module to getting a SSL_CTX provided by ssl or proxy modules, create a new thread that will be updating SSL_CTX with provided certificates from SPIRE, 

to accomplish it, we'll need to:

- Update SPIFFE module to update SSL_CTX instead of restarting nginx.
- remove directives "svid_file_path", "svid_key_file_path" and "svid_bundle_file_path".
- update ssl/proxy modules to provide SSL_CTX to SPIFFE module.
- Remove the use of cert files and use in memory instead.
- update code to no longer depends of ssl/proxy cerficicate directives
- validate certificates using the same logic nginx is actually using when its starting.

**Comment by MarcosDY** [comment]
Changes merged, 
* Module was refactored to consume certificates as DER and process to push them into SSL_CTX, 
* Old directives to specify files paths were removed (those are no longer neccesary)
* Example config files updated with new approach.
* Still using SIGHUP it was no necesarry remove it, because with new approach it is working as expected.

**Comment by evan2645** [comment]
@MarcosDY can you link to the PRs that committed the changes so we can have them for the future? After that we can close this issue

**Comment by MarcosDY** [comment]
Addressed in #13
